name: Build & Restart Pterodactyl Server

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma Client
        run: npm run prisma:generate
        env:
          DATABASE_URL: "postgresql://user:pass@localhost:5432/db"

      - name: Build project
        run: npm run build

      - name: Restart Pterodactyl server
        run: |
          curl -X POST "${{ secrets.PTERO_URL }}/api/client/servers/${{ secrets.SERVER_ID }}/power" \
          -H "Authorization: Bearer ${{ secrets.PTERO_KEY }}" \
          -H "Content-Type: application/json" \
          -H "Accept: Application/vnd.pterodactyl.v1+json" \
          -d '{"signal":"restart"}'